### ISSUE TITLE
Unable to locate the 'ticks' parameter in the metadata

### ISSUE THREAD

**Issue by anirudh3** [asigalov61/Los-Angeles-MIDI-Dataset#1]
Thank you so much for this dataset. I'm currently exploring and playing around with it, however I think I may be missing something very basic here. 

I used the unpacked meta_data from here
`meta_data = pickle.load(open('/home/s_ani/home/datasets_lemo/LA_midi/Los-Angeles-MIDI-Dataset/META-DATA/LAMDa_META_DATA.pickle', 'rb')) `

And when I check for one MIDI, I couldn't find the 'ticks' required by the opus2midi function from MIDI.py:
```
def opus2midi(opus=[]):
    r'''The argument is a list: the first item in the list is the "ticks"
parameter, the others are the tracks. Each track is a list
of midi-events, and each event is itself a list; see above.
opus2midi() returns a bytestring of the MIDI, which can then be
written either to a file opened in binary mode (mode='wb'),
or to stdout by means of:   sys.stdout.buffer.write()
```

The only information I do have is set_tempo, and I'm wondering how to come up with the 'ticks' parameter. I hope to thereafter write out like a MIDI file. Maybe this is not the intended way to load and use this dataset, or maybe I'm missing some understanding of the 'ticks' concept. Any help/suggestions would be very helpful!

Thanks.

**Comment by asigalov61** [comment]
@anirudh3 Hello! Sorry for the delayed response.

You are absolutely right about the missing "ticks" parameter. It was not recorded when I collected the metadata from midis. I am working on correcting this problem, as well as other issues with the dataset (which is why it is currently offline) and hopefully the next release will be problems free.

Metadata was mostly collected to provide general info about each midi. It was not intended to be converted back to midi. But ticks parameter is important so I will include it in the next release of the metadata.

Hope this answers your question and I am sorry about any confusion or wasted time.

Alex.

**Comment by anirudh3** [comment]
Thanks for the response @asigalov61! Few quick follow ups if I may:
1 - Is there an ETA on the new release maybe?
2 - I used a default "ticks" param value of 96, but I believe that would be wrong, seems to work for a few. Is there a way for me to still use this, or a workaround? Happy to wait for this wonderful dataset, but wondering if I can experiment with it right away
3 - Do you plan to include the scale/key information in the new release as well? I'm relatively new to MIDI, so any suggestions on estimation algorithms/packages for that are welcome

Thanks again, and I look forward to the new release.

**Comment by asigalov61** [comment]
@anirudh3 

You are welcome :)

To answer your questions:

1) I plan to update the metadata soon (within a week or two). I am a one-man operation so things take time :)

2) Unfortunately, you need the correct ticks value to restore the original midis from the metadata as it appears. There is no real workaround to this. Sorry.

3) RE: scale/keys, other stuff: MIDI.py (and opus2midi) collects all info included in the midis. Not all midis have that info so the only way to get it is to analyze the original midi and guess or calculate these values.

4) There are some MIDI packages that can guess that info. I think pretty_midi has a bunch of useful functions in this regard. Also check out https://github.com/salu133445/muspy and https://github.com/CPJKU/partitura and https://github.com/Rainbow-Dreamer/musicpy

Otherwise, thank you for your interest and feedback about the dataset. I really appreciate it. :) I will let you know once I post the updates so that you can download the updated version.

Sincerely,

Alex

**Comment by anirudh3** [comment]
Thank you so much! I appreciate it, and hopefully in the future I can add to this wonderful package as well :)

**Comment by asigalov61** [comment]
@anirudh3 Just letting you know that I posted version 2.0 of the dataset. Check it out and let me know what you think or if there are any issues.

Thanks.

**Comment by anirudh3** [comment]
Thank you, will do :)
