### ISSUE TITLE
Where do the chords come from?

### ISSUE THREAD

**Issue by rubencart** [asigalov61/Los-Angeles-MIDI-Dataset#2]
Did you automatically extract/predict them? If so, how?

Do you have a paper or report that you can share, on how you collected the data etc?

**Comment by asigalov61** [comment]
@rubencart Thank you for your question...

Chords data is sorta a WIP so I apologize for lack of description...

LAMDa chords is included in the LAMDa archive (which you can download from Hugging Face) and you can decode it by using provided code in the CHORDS_DATA dir of the repo.

LAMDa chords are presented in the MIDI pitch format (0-127) + drums (128-256).

I did not use the standard music notation because its not sufficient to describe chords of complex music compositions/multi-instrumental music.

However, my TMIDIX module provides a set of tools to process LAMDa CHORDS DATA into more conventional notation. My tegridy-tools also have a set of tools to do the same.

Hope this answers your question but if not, I would be happy to elaborate more :)

Alex

**Comment by asigalov61** [comment]
@rubencart I've updated the CHORDS DATA readme with basic info. I will provide more details soon so please stand by.

**Comment by asigalov61** [comment]
@rubencart I am closing this issue for now. But feel free to re-open if needed.

Alex.

**Comment by rubencart** [comment]
Great, thanks!

**Comment by rubencart** [comment]
It would be great if there was a technical report or a publication that explains details, and that I could cite if I use the dataset for research though!

**Comment by asigalov61** [comment]
@rubencart You are welcome :)

I plan to make a detailed statistical report on the dataset but it may be a while because I am a bit behind on documentation. Sorry.

Otherwise, you can use a citation on the main page of the repo if you want to cite the dataset itself.

**Comment by asigalov61** [comment]
@rubencart 

Some statistical data and graphs is available here:
https://colab.research.google.com/github/asigalov61/Los-Angeles-MIDI-Dataset/blob/main/Los_Angeles_MIDI_Dataset_Search_and_Explore.ipynb

You can also use this colab to review the metadara.
