### ISSUE TITLE
Question about MIDI's folder

### ISSUE THREAD

**Issue by adricl** [asigalov61/Los-Angeles-MIDI-Dataset#3]
Hello Alex,

I have downloaded your dataset and I was wondering with the MIDI folder is there some sort of break down as to the 0-9 A-F other than just a hex value? Is each folder essentially random? 

Thanks for all your hard work.

**Comment by asigalov61** [comment]
@adricl Thank you for your question :)

Yes, the MIDIs were split by their md5 hash value (first letter of the md5 hash), so the distribution across all 16 folders is pretty much random.

This is why I provided the code/colabs so that you could search and navigate the dataset. I highly recommend you check it out.

Here is the best and latest colab notebook:

https://colab.research.google.com/github/asigalov61/Los-Angeles-MIDI-Dataset/blob/main/Extras/Master_MIDI_Dataset_GPU_Search_and_Filter.ipynb

Hope this answers your questions and thank you for appreciating my work. it means a lot to me :)

Alex

**Comment by adricl** [comment]
Thanks for your response I will take a look, the amount of MIDIs is really taxing my hardware lol. I have been working on this dataset with this notebook https://github.com/Natooz/MidiTok/blob/main/colab-notebooks/Example_HuggingFace_Mistral_Transformer.ipynb seeing what I can come up with. Thanks for all your hard work in this.
