### ISSUE TITLE
Documentation of the notebooks

### ISSUE THREAD

**Issue by DanielJonasMielke** [asigalov61/Los-Angeles-MIDI-Dataset#4]
Hey man! 

First of all much appreciation for your work, we certainly do not take it for granted. 
I´m sort of new to the ML stuff and working with datasets, especially when it comes to complex stuff like contextualization inside of a MIDI dataset. 
So I´ve got a couple of questions for downloading the dataset (v4). 

1. How do those signatures work? Following the code the output of that snippet would result in somth like this: 
["filename", [(0, 0.12), (1, 0.45), (256, 0.78)]] What do those indexes and values exactly represent? 

2. Master MIDI Dataset Search and Filter --> Here you basically want us to upload target MIDI files (for example ones from a specific genre such as classic, pop, lofi, chords or melodies), right? The script then goes ahead and tries to match those target MIDIs with the ones from the dataset. 

2.1 number_of_top_matches_MIDIs_to_collect: Means for every single target MIDI I upload the dataset searches a maximum of 50 matches? So if I want to have a dataset with the size of 10.000 MIDI files I would have to upload 200 MIDI files (with the parameter set to 50) 

2.2 maximum_match_ratio_to_search_for: Why set a maximum and not a minimum for the matching accuracy? 

2.3 match_results_weight: what is that for? 

2.4 distances_norm_order: what is that for? 

2.5 epsilon: what does epsilon represent in that case? 

3. **Load Los Angeles MIDI Dataset Kilo-Chords Data** what is this whole Kilo-Chord thing about? Also what does "Kilo" stand for? 

4. Master MIDI Dataset Search and Filter -->Why Search and Filter a second time? Should I use the same Target midis again? 

I hope those ain´t too many questions and would really appreciate some answers to them for newbies:) 

Cheers and thank you very much!

**Comment by asigalov61** [comment]
@MielkeDaniel Hey Daniel,

Thank you for appreciating my work. It means a lot to me :)

I apologize for lack of description/documentation for the dataset. I am way behind on that, but I would be happy to answer all of your questions. :)

1) Signatures are simple Counts of pitches, chords, and drums pitches. So [60, 15] == 60 pitch (C4) -- 15 count. Please note that chords and drums numbers are shifted to avoid ambiguity.

2) Yes, Master MIDI Dataset Search and Filter will help to find exact of similar MIDIs in the dataset. There are several search options to choose from and you can upload any MIDIs you like. They do not have to be of one kind.

2.1) Yes, you are correct.  number_of_top_matches_MIDIs_to_collect indicates how many matches to collect. So yes, if you want to collect total of 10000 MIDIs from the dataset, you will need 200 source MIDIs.

2.2) maximum_match_ratio_to_search_for Its maximum because you usually want top matches. However, you can easily modify the code if you want to have only minimum or both. I can help with that.

2.3) match_results_weight Since during search the algorithm tries to take into account several factors to find best possible match, you can assign the significance to the factors such as match ratio to get different results. This is optional and it was set/tuned to most optimal. However, play with it and see what works for you.

2.4) distances_norm_order This is only for distances search option. Which distance to use basically... 2 == euclidian, 3 = minkowski, etc

2.5) epsilon value is to avoid division by zero. It does not really affect the search results, except for extreme search cases.

3) Kilo-chords is referring to search matching type (1000 == a thousand chords). The algorithm uses first 1000 notes/chords from each MIDI file in the dataset to do the matching. Sometimes this search produces better results.

4) This is just a bad colab note. All search options will use the same Master-MIDI-Dataset folder/MIDIs. You do not need to reupload it every or each time.

I hope this answers your qeustions. If not, I would be happy to elaborate further or answer more of your questions :)

Sincerely,

Alex.

PS. Please note that Los Angeles MIDI Dataset is kinda old and I am trying to phase it out in favor of my Monster MIDI dataset which is a superset of Los Angeles MIDI dataset and has all of the same features but with significant improvements. So make sure to check it out:

https://github.com/asigalov61/Monster-MIDI-Dataset

**Comment by asigalov61** [comment]
@MielkeDaniel Couple of pointers:

1) Make sure to try/use GPU version of Master MIDI Datset Search and Filter as it works much faster (uses GPU), especially on many source MIDIs.

2) Ratio search is the best search so for best results use Ratio search matching option. Other options are usually less precise.

**Comment by DanielJonasMielke** [comment]
@asigalov61  Oh wow, first of all thank you so much for taking the time to respond to every question I had, that definetly helped me clarify things a lot! And I will definetly take closer look into the monster midi ds right after this :) 

Yesterday I downloaded a first version for myself with 570 target MIDIs, that I have uploaded. 
So the final result is this folder, where there is a subfolder for each uploaded MIDI, which then includes the custom MIDI itself + the matches found from the dataset. 
After analyzing the downloaded dataset in Ableton I realized, that there were quiet a few duplicates in each subfolder. 
Is this expected? 

Since I´m still new to this topic I actually also have many other questions related to the whole training process, optimizing the dataset and more. Is there potentially something like a community discord server or so for Project Los Angeles or artificial music generation in general where I could share them?

**Comment by asigalov61** [comment]
@MielkeDaniel You are very welcome :)

Yes, duplicates in the matches are expected because there is not really a way to check for that for similar MIDIs (i.e a version of a composition with slightly different instruments). Also, popular compositions may have many duplicates because they all slightly different MIDIs. Dataset was only deduped by MIDIs md5 hashes, not by content of MIDIs.

In regard to questions... Its best to open an issue or start a discussion in the respective repos you are interested in so that other people can benefit from it too.

Otherwise, you can email me at alexlev61@proton.me for DMs and so that I can send you a private Discord channel.

Hope this helps.

Alex ;)

**Comment by DanielJonasMielke** [comment]
Alright, good to know thank you! 

As for the questions, I will gladly send you an email to not further digress from this issue! All questions I had regarding this dataset have been mostly solved:) 

Daniel

**Comment by asigalov61** [comment]
@MielkeDaniel Glad it was helpful :)

I've got your email. I will respond soon :)

Alex
